Models/ErrorViewModel.cs
namespace la_mia_pizzeria_static.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Pizza.cs
namespace la_mia_pizzeria_static.Models
{
    public class Pizza
 {
        public string Nome { get; set; }
        public string Descrizione { get; set; }
        public string Immagine { get; set; }
        public double Prezzo { get; set; }

        public Pizza(string nome, string descrizione, string immagine, double prezzo)
        {
            Nome = nome;
            Descrizione = descrizione;
            Immagine = immagine;
            Prezzo = prezzo;
        }
    }
}

Controllers/EserciziController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class EserciziController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Esercizi/Index.cshtml
@{
    string name = "Fabio";
    string lastName = "Moro";
    int randomNumber;

    DateTime thisDay = DateTime.Now;

    List<int> Lista = new List<int>();

    for(int i =0; i < 20; i++) {
        randomNumber = new Random().Next(90);
        Lista.Add(randomNumber);
    }

    int SommaNumeri(int n) {

        int somma = 0;

        for(int i = 1; i <= n; i++) {
            somma = somma + i;
        }

        return somma;
    }

    int ContaLettera() {

        int cont = 0;

        string sentence = "nel mezzo del cammin di nostra vita";

        for(int i = 0; i < sentence.Length; i++) {
            if(sentence[i].CompareTo('a') == 0) {
                cont = cont + 1;
            }
        }

        return cont;
    }

}

 <h2>Esercizio 1: @name @lastName</h2>

 <h2>Esercizio 2:</h2> 
 <span>@SommaNumeri(10)</span>

 <h2>Esercizio 3: @ContaLettera()</h2>

 <h2>Esercizio 4: </h2>
 @foreach(int numero in Lista) {
     @if(numero >= 20 & numero < 70) {
         <span>@numero</span>
     }
 }

<h2>Esercizio 5: </h2>
<span>@thisDay</span>
 

Views/Home/Index.cshtml
@{
    List<Pizza> ListaPizze = new List<Pizza>();
    Pizza margherita = new Pizza("Margerita", "Mozzarella e Pomodoro", "https://www.tavolartegusto.it/wp/wp-content/uploads/2020/05/Pizza-napoletana-Ricetta-della-Pizza-Napoletana-Pizza-Margherita.jpg", 5.99);
    Pizza napoli = new Pizza("Napoli", "Mozzarella, Pomodoro e Alici", "https://www.donnamoderna.com/content/uploads/2021/08/pizza-napoli.jpg", 6.99);
    Pizza diavola = new Pizza("Diavola", "Salame piccante", "https://www.misya.info/wp-content/uploads/2007/08/Pizza-alla-diavola.jpg", 7.99);
    ListaPizze.Add(margherita);
    ListaPizze.Add(napoli);
    ListaPizze.Add(diavola);
}

@foreach(Pizza pizza in ListaPizze) {
    <div>
        <div>@pizza.Nome</div>
        <div>@pizza.Descrizione</div>
        <image src="@pizza.Immagine" style="width: 200px"></image>
        <div>@pizza.Prezzo</div>
    </div>
}


    

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - la_mia_pizzeria_static</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PrimoSito</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Esercizi" asp-action="Index">Esercizi</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - la_mia_pizzeria_static - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>